---
- hosts: webservers
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Instalando o Nginx
    package:
      name: nginx
      state: latest
      update_cache: yes

  - name: Habilitando start nginx no boot
    service:
      name: nginx
      enabled: yes
      
  - name: Iniciando o Nginx
    service: 
      name: nginx
      state: started


  - name: Criando um template em jinja
    template:
      src: index.html.j2
      dest: /var/www/html/index.html

  - name: Copiando index.html
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  handlers:
  - name: restartando nginx
    service:
      name: nginx
      state: restarted