- name: Creating Security Group
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group Giropops
    region: "{{ region }}"
    profile: "{{ aws_profile }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Creating EC2 instance
  local_action: ec2
    group={{ security_group }}
    instance_type={{ instance_type }}
    image={{ image }}
    profile="{{ aws_profile }}"
    wait=true
    region={{ region }}
    keypair={{ keypair }}
    count={{ count }}
  register: ec2


- name: Add instances to temporary inventory
  add_host: name={{ item.public_ip }} groups=teste-new
  with_items: "{{ ec2.instances}}"


- name: Add Public IP to host file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter=" [ kubernetes ] " line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Add Private IP to host file
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.private_ip }}
    insertafter=" [ kubernetes ] " line={{ item.private_ip }}
  with_items: "{{ ec2.instances }}"


- name: Wait SSH
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: "{{ ec2.instances }}"


- name: ADD tag 
  local_action: ec2_tag resource={{ item.id }} region={{ region}}  profile={{ aws_profile }} state=present
  with_items: "{{ ec2.instances }}"
  args: 
    tags:
      Name: ansible-{{ item.ami_launch_index|int +1 }}      